module.exports = [
	{
		rx: 'Acetaminophen',
		generic: 'Tylenol',
		dosage: '325mg',
		frequency: 'As needed',
		quantity: 100,
		use: 'Pain Reliever',
		why: 'Relieve Pain or Reduce Fever',
		description: 'Acetaminophen is used to treat mild to moderate pain, moderate to severe pain in conjunction with opiates, or to reduce fever. Common conditions treated include headache, muscle aches, arthritis, backache, toothaches, sore throat, colds, flu, and fevers.',
		side: 'Stomach Pain (Upper Right Side), Loss of Appetite, Tiredness, Itching, Dark Urine, Clay-Colored Stools, or Jaundice',
		serious: 'Severe Skin Reaction, Ongoing Headache, Nausea, Vomiting, Redness, Swelling, if your symptoms get worse, or if you have any new symptoms',
		major: 7,
		moderate: 65,
		minor: 35,
		interactions: 'https://www.drugs.com/drug-interactions/acetaminophen.html',
	},
	{
		rx: 'Amphetamine',
		generic: 'Adderall',
		dosage: '5mg',
		frequency: 'Twice Daily',
		times: '8:00,23:00',
		quantity: 30,
		use: 'Central Nervous System Stimulant',
		why: 'Treat ADHD',
		description: 'Adderall is used to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy. Adderall contains a combination of amphetamine and dextroamphetamine.',
		side: 'Stomach Pain, Loss of Appetite, Weight Loss, Mood Changes, Feeling Nervous, Fast Heart Rate, Headache, Dizziness, Sleep Problems, or Dry Mouth',
		serious: 'Chest Pain, Trouble Breathing, Hallucinations, Aggression, Hostility, Paranoia, Seizures, Tics (Muscle twitches), or Changes in your Vision',
		major: 36,
		moderate: 135,
		minor: 9,
		interactions: 'https://www.drugs.com/drug-interactions/amphetamine-dextroamphetamine,adderall.html',
	},
	{
		rx: 'Naproxen',
		generic: 'Aleve',
		dosage: '250mg',
		frequency: 'As needed',
		quantity: 30,
		use: 'Nonsteroidal Anti-Inflammatory Drug',
		why: 'Relieve Pain or Reduce Inflammation',
		description: 'Naproxen is a nonsteroidal anti-inflammatory drug (NSAID). It works by reducing hormones that cause inflammation and pain in the body.',
		side: 'Indigestion, Heartburn, Stomach Pain, Nausea, Headache, Dizziness, Drowsiness, Bruising, Itching, Rash, Swelling, or Tinnitus (Ringing in the ears)',
		serious: 'Shortness of Breath, Swelling, Rapid Weight Gain, Skin Reaction, Liver Issues, Kidney Issues, or Anemia',
		major: 94,
		moderate: 286,
		minor: 18,
		interactions: 'https://www.drugs.com/drug-interactions/naproxen,aleve.html',
	},
	{
		rx: 'Diphenhydramine',
		generic: 'Benadryl',
		dosage: '50mg',
		frequency: 'As needed',
		quantity: 20,
		use: 'Antihistamine',
		why: 'Relieve Allergy Symptoms',
		description: "Benadryl is an antihistamine that reduces the effects of natural chemical histamine in the body. Benadryl is also used to treat motion sickness, to induce sleep, and to treat certain symptoms of Parkinson's disease.",
		side: 'Dizziness, Drowsiness, Loss of Coordination, Constipation, Upset Stomach, Dry Eyes, Dry Mouth, Dry Nose, Dry Throat, or Blurred Vision',
		serious: 'Pounding Heartbeats, Painful or Difficult Urination, Confusion, Tightness in your Neck or Jaw, or Uncontrollable Movements of your Tongue',
		major: 13,
		moderate: 399,
		minor: 2,
		interactions: 'https://www.drugs.com/drug-interactions/diphenhydramine,benadryl.html',
	},
	{
		rx: 'Ibuprofen',
		generic: 'Advil',
		dosage: '200mg',
		frequency: 'As needed',
		quantity: 150,
		use: 'Nonsteroidal Anti-Inflammatory Drug',
		why: 'Relieve Pain or Reduce Inflammation',
		description: 'Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID). It works by reducing hormones that cause inflammation and pain in the body.',
		side: 'Nausea, Vomiting, Gas, Bleeding, Dizziness, or Headache',
		serious: 'Changes in Vision, Shortness of Breath, Swelling, Rapid Weight Gain, Skin Reaction, Liver Issues, Kidney Issues, or Anemia',
		major: 94,
		moderate: 260,
		minor: 14,
		interactions: 'https://www.drugs.com/drug-interactions/ibuprofen.html',
	},
	{
		rx: 'Melatonin',
		generic: 'Melatonin',
		dosage: '5mg',
		frequency: 'Every night',
		times: '21:30',
		quantity: 60,
		use: 'Sedative',
		why: 'Sleep',
		description: 'Melatonin is the natural hormone your body secretes that helps to maintain your wake-sleep cycle (also called “biological clock”).',
		side: 'Drowsiness, Dizziness, Weakness, Confusion, Vivid Dreams, Headache, Loss of Appetite, Diarrhea, Nausea, Stomach Pain, or Joint or Back Pain',
		serious: 'Nightmares, Depression, Anxiety, Increased Irritability, Changes in Blood Pressure, or Seizures',
		major: 0,
		moderate: 282,
		minor: 7,
		interactions: 'https://www.drugs.com/drug-interactions/melatonin.html',
	},
	{
		rx: 'Omeprazole',
		generic: 'Prilosec',
		dosage: '20mg',
		frequency: 'As needed',
		quantity: 60,
		use: 'Proton Pump Inhibitor',
		why: 'Relieve Heartburn',
		description: 'Omeprazole works by blocking gastric acid production and is from the group of medicines called proton pump inhibitors.',
		side: 'Cold Symptoms, Fever, Stomach Pain, Gas, Nausea, Vomiting, Diarrhea, or Headache',
		serious: 'Severe Stomach Pain, Seizures, Kidney Issues, Dizziness, Irregular Heartbeats, Feeling Jittery',
		major: 21,
		moderate: 142,
		minor: 47,
		interactions: 'https://www.drugs.com/drug-interactions/omeprazole,prilosec.html',
	},
]
